image: registry.cn-hangzhou.aliyuncs.com/handsometech/leancloud:1.6
stages:
    - build
    - deploy
    - test

cache:
    paths:
    - node_modules/

build:
    stage: build
    script:
        - cnpm install

deploy:
    stage: build
    script:
        - autologin.expect
        - lean deploy
        
test:
    stage: test
    script:
        - cnpm test