image: registry.cn-hangzhou.aliyuncs.com/handsometech/leancloud:1.6
stages:
    - build
    - test-deploy
    - deploy
cache:
    paths:
    - node_modules/

build:
    stage: build
    script:
        - cnpm install

test-deploy:
    stage: test-deploy
    script:
        - autologin.expect
        - lean deploy
        
    
deploy:
    stage: deploy
    script:
        - docker build -t registry.cn-hangzhou.aliyuncs.com/handsometech/leancloud:1.6
        - autologin.expect
        - lean deploy
